apache/causeway

core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/InteractionHelper.java
When invoking newCollectionInteractionEvent(...) a null value is passed to the phase, causing an exception to be thrown.
=> InteractionHelper.postEventForCollection: Phase parameter is null

core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/DomainEventHelper.java
It can reuse an Event not corresponding to the same "domain action" on a previous phase (which I suppose was the main intention for reusing).
=> Update DomainEventHelper for not reusing ThreadLocal event

core/applib/src/main/java/org/apache/isis/applib/services/exceprecog/ExceptionRecognizerComposite.java
I have implemented ApplicationTenancy.
When directly introducing the URL of an entity whose access is forbidden for me (i.e., http://localhost:8080/entity/KIT_:L_2) throws a NullPointerException.
Perhaps the root cause is different.
But simply by evaluating if is null, it properly shows the error message ("Not authorized or no such object") instead of a HTTP 500 with a NullPointerException in the log.
=> ExceptionRecognizerComposite: NPE if container is null

core/pom.xml, core/security-shiro/src/main/java/org/apache/isis/security/shiro/IsisLdapRealm.java
I propose new permisions creation from LDAP attribute
Alternatively, permissions can be extracted from the base itself with the parameter searchUserBase,
the attribute list as userExtractedAttribute and the permission url as permissionByUserAttribute.
The idea is to extract attribute from the user or the group of the user and map directly to permission rule in replacing the string {attribute} by the extracted attribute (can me multiple).
See the sample for group and user attribute and mapping:
ldapRealm.searchUserBase = ou=users,o=mojo
ldapRealm.userObjectClass=inetOrgPerson
ldapRealm.userObjectClass=organizationnalPerson
ldapRealm.groupExtractedAttribute=street,country
ldapRealm.userExtractedAttribute=street,country
ldapRealm.permissionByGroupAttribute=attribute:Folder.{street}:Read,attri …
=> ISIS-1162 Add attribute for permission ldap extraction

adocs/documentation/src/main/asciidoc/index.html
Fix the broken link under simpleapp-archetype on the main http://isis.apache.org page by linking it correctly to "guides/ug.html#_ug_getting-started_simpleapp-archetype" URL fragment instead of the current non-existent one.
=> ISIS-1181: Fix broken link on main http://isis.apache.org

adocs/documentation/src/main/asciidoc/guides/_rgant-Action_domainEvent.adoc, adocs/documentation/src/main/asciidoc/guides/_rgant-Collection_domainEvent.adoc, adocs/documentation/src/main/asciidoc/guides/_rgant-Property_domainEvent.adoc
Ran into some deprecated statements in the isis documentation.
=> Replaced deprecated getPhase() with getEventPhase() in documentation

adocs/documentation/src/main/asciidoc/guides/_ugfun_object-layout_dynamic_xml.adoc
Link to unreferenced members was pointing towards the classes, methods and schema guide rather than the fundamentals guide
=> Fixed link in docs

core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/isisapplib/IsisBlobOrClobPanelAbstract.java
Consider we want for a file-upload (Blob/Clob property) to allow only specific file extensions!
HTML file input tags allow for the client-side file-open-dialog to filter for specific file types *.xyz via the `<input ... accept=".xyz"/>` attribute.
This DEMO shows how we can exploit this feature for Blob/Clop properties. 
Note however, that the newly introduced `getAcceptFilter()` method needs to be changed. For this DEMO we 'borrow' the intended filter info from the `discribedAs` option as e.g. in `@ParameterLayout(named="File", describedAs=".xlsx")} `.
=> Blob/Clob: File-extension filter for client-side file-open-dialog

core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/pages/accmngt/AccountManagementPageAbstract.java
Checked the ToDo-app first and the screencast for changing the application name. It seems the annotation should be there.
=> ISIS-1475: Named-annotation disappeared on AccountManagementPageAbstract

core/viewer-wicket-impl/src/main/java/org/apache/isis/viewer/wicket/viewer/imagecache/ImageResourceCacheClassPath.java
Fixes a typo in the image suffix list. ".svg" -> "svg"
=> Fix 'svg' suffix in ImageResourceCacheClassPath

core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/value/datetimejodalocal/JodaLocalDateTimeValueSemanticsProvider.java
JodaLocalDateTimeValueSemanticsProvider,
given that 
```
encodingFormatter = ISODateTimeFormat.basicDateTime()
```
assumes that 
```
date == encodingFormatter.parseLocalDateTime(
encodingFormatter.print(date)
)
```
which is not true (at least for the latest ver. 2.9.4 of joda-time). Instead following code snipped will throw an exception:
```
final DateTimeFormatter encodingFormatter = ISODateTimeFormat.basicDateTime();
encodingFormatter.parseLocalDateTime(
encodingFormatter.print(new org.joda.time.LocalDateTime()));
...
java.lang.IllegalArgumentException: Invalid format: "20160910T083301.000" is too short
```
Provided solution conforms to Java 8 `java.time.format.DateTimeFormatter.ISO_LOCAL_DATE_TIME` which uses `yyyy-MM-dd'T'HH:mm:ss` format.
=> Fix DateTime marshalling in JodaLocalDateValueSemanticsProvider

adocs/documentation/src/main/asciidoc/guides/rgcms/_rgcms_methods_reserved_disable.adoc
At least in Apache ISIS version 1.15.0 only the method name disabled() works as described. The only other source I found is a comment in the corresponding feature request:
https://issues.apache.org/jira/browse/ISIS-142?focusedCommentId=13165135&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13165135
=> Update disable() to disabled()

core/applib/src/main/java/org/apache/isis/applib/services/repository/RepositoryService.java, core/config/src/main/java/org/apache/isis/config/ConfigurationConstants.java, core/config/src/main/java/org/apache/isis/config/IsisConfigModule.java, core/config/src/main/java/org/apache/isis/config/IsisConfigProperties.java, core/metamodel/src/main/java/org/apache/isis/metamodel/services/repository/RepositoryServiceJdo.java, core/metamodel/src/main/java/org/apache/isis/metamodel/specloader/specimpl/FacetedMethodsBuilder.java, core/pom.xml, core/runtime-extensions/src/main/java/org/apache/isis/runtime/spring/IsisBoot.java, examples/apps/helloworld/src/main/java/domainapp/application/isis-non-changing.properties, examples/apps/helloworld/src/main/resources/application.properties
- First is "isis.services.container.disableAutoflush", which is used by RepositoryServiceJdo.  Here the config bean can be injected and consumed directly.
- Second is "isis.reflector.explicitAnnotations.action", which is used by FacetedMethodBuilder.  Here we use the _Spring.getSingleton service locator to read.
Note: just the start of a hole bunch of similar config conversion steps
=> ISIS-2082: spikes the use of type-safe config properties, for two cases.

core/pom.xml, viewers/restfulobjects/applib/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
=> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

antora/components/comguide/modules/ROOT/pages/antora-publish-procedure.adoc, antora/components/comguide/modules/ROOT/pages/verifying-releases.adoc, antora/components/docs/modules/ROOT/pages/going-deeper/articles-and-presentations.adoc, antora/components/docs/modules/ROOT/pages/going-deeper/books.adoc, api/adoc/userguide/modules/fun/pages/concepts-patterns/architecture.adoc, api/applib/src/main/adoc/modules/applib-svc/pages/RoutingService.adoc, api/applib/src/main/adoc/modules/applib-svc/pages/SudoService.adoc, api/applib/src/main/adoc/modules/applib-svc/pages/TableColumnOrderService.adoc, api/applib/src/main/adoc/modules/applib-svc/pages/_BackgroundService.adoc, api/applib/src/main/adoc/modules/applib-svc/pages/about.adoc, api/schema/src/main/adoc/modules/schema/pages/chg.adoc, api/schema/src/main/adoc/modules/schema/pages/cmd.adoc, core/runtimeservices/src/main/adoc/modules/runtime-services/pages/ContentNegotiationService.adoc, core/runtimeservices/src/main/adoc/modules/runtime-services/pages/PublisherDispatchService.adoc, core/runtimeservices/src/main/adoc/modules/runtime-services/pages/RepresentationService.adoc, testing/adoc/modules/ROOT/pages/about.adoc, viewers/wicket/adoc/modules/ROOT/pages/extending/replacing-page-elements.adoc
For the AsciiDoc plugin for IntelliJ I'm currently implementing a link checker for xrefs and anchors and I used the Apache Isis project to "train" it.
This PR fixes some of the links I was able to fix from their respective contexts. Please double-check if I chose the correct target for each link.
To find more broken links, install the latest IntelliJ plugin for AsciiDoc (0.30.56+) and run "Analyze | Inspect code...". I found it helpful to setup an inspection profile for only AsciiDoc checks.
(cc: @danhaywood)
=> ISIS-2356: fix broken links and anchors in docs

extensions/security/secman/api/src/main/java/org/apache/isis/extensions/secman/events/UserCreatedEvent.java, extensions/security/secman/api/src/main/java/org/apache/isis/extensions/secman/events/package-info.java, extensions/security/secman/persistence-jdo/src/main/java/org/apache/isis/extensions/secman/jdo/dom/user/ApplicationUserRepository.java
The real work of adding default roles is in the client application.  I committed this after testing my client application receiving and using this new event to add default roles to delegated users.
=> Secman now sends a UserCreatedEvent

api/schema/build.gradle, build.gradle, core/metamodel/build.gradle, core/runtimeservices/build.gradle, subdomains/xdocreport/applib/src/test/java/org/apache/isis/subdomains/xdocreport/applib/service/XDocReportServiceTest.java, testing/fakedata/applib/build.gradle
Adds XJC task for jaxb in shema project.
Also, in a few projects, adds non-java resources from `src/main/java` to build folder [gradle] as they are excluded by default.
=> JAXB Gradle plugin implementation

examples/demo/wicket/pom.xml
https://issues.apache.org/jira/browse/ISIS-2421
Signed-off-by: Brian Kalbfus <harvestmoon299@gmail.com>
=> Allows fat jar to start without error finding asciidoctor in jruby.

antora/components/docs/modules/ROOT/pages/what-is-apache-isis/powered-by/gesconsultor-grc.adoc, antora/components/refguide-index/modules/_overview/pages/about.adoc, examples/demo/wicket/e2e-notes.adoc, examples/demo/wicket/src/test/e2e/cypress-scaffolding/integration/typescript/basic.ts, examples/demo/wicket/src/test/e2e/tsconfig.json, extensions/vw/fullcalendar/pom.xml, extensions/vw/pdfjs/ui/src/main/java/org/wicketstuff/pdfjs/res/pdf.js, viewers/wicket/adoc/modules/ROOT/pages/customisation/auto-refresh.adoc, viewers/wicket/adoc/modules/ROOT/pages/customisation/custom-javascript.adoc
Changes are:
- `javascript` -> `JavaScript`
- `typescript` -> `TypeScript`
=> chore: fix case of JavaScript and TypeScript

commons/src/main/java/org/apache/isis/commons/collections/Can.java, commons/src/main/java/org/apache/isis/commons/internal/base/_Text.java, commons/src/main/java/org/apache/isis/commons/internal/debug/xray/sequence/SequenceDiagram.java, commons/src/main/java/org/apache/isis/commons/internal/debug/xray/sequence/_Graphics.java, core/config/src/main/java/org/apache/isis/core/config/IsisModuleCoreConfig.java, core/interaction/src/main/java/org/apache/isis/core/interaction/session/InteractionTracker.java, core/pom.xml, core/runtime/src/main/java/org/apache/isis/core/runtime/events/_Xray.java, core/runtime/src/main/java/org/apache/isis/core/runtime/util/XrayUtil.java, core/runtimeservices/src/main/java/org/apache/isis/core/runtimeservices/executor/MemberExecutorServiceDefault.java, core/runtimeservices/src/main/java/org/apache/isis/core/runtimeservices/executor/_Xray.java, core/runtimeservices/src/main/java/org/apache/isis/core/runtimeservices/session/InteractionFactoryDefault.java, core/runtimeservices/src/main/java/org/apache/isis/core/runtimeservices/session/_Xray.java, examples/demo/wicket/src/main/java/demoapp/webapp/wicket/DemoAppWicket.java, isis-parent/pom.xml, starters/pom.xml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/isis/438)
=> Resurrect Entity Change Tracking Regression Tests for the JDO Stack

incubator/clients/kroviz/src/main/kotlin/org/apache/isis/client/kroviz/ui/kv/DropdownSearch.kt, incubator/clients/kroviz/src/main/kotlin/org/apache/isis/client/kroviz/ui/kv/EventChart.kt, incubator/clients/kroviz/src/main/kotlin/org/apache/isis/client/kroviz/ui/kv/RoApp.kt, incubator/clients/kroviz/src/main/kotlin/org/apache/isis/client/kroviz/ui/kv/RoTabPanel.kt
The root width was previously set to 100pc, this caused the TabPanel to not be 100% width even if set to 100%. By setting both the root (RoApp) and TabPanel widths to 100% the Tab-layout now is in fact, 100% width.
=> ISIS-2346 - Tab Layout isn't using 100% Width

viewers/wicket/ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/jodatime/ConverterForJodaLocalTime.java, viewers/wicket/ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/jodatime/JodaLocalTimePanel.java, viewers/wicket/ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/jodatime/JodaLocalTimePanelFactory.java, viewers/wicket/viewer/src/main/java/org/apache/isis/viewer/wicket/viewer/registries/components/ComponentFactoryRegistrarDefault.java
Without this patch applied, input to a joda LocalTime field causes an error.
This patch fixes the problem by adding a panel to be used by joda LocalTime.
=> ISIS-2063: Entering a string for a joda LocalTime causes an error

api/applib/src/main/java/org/apache/isis/applib/events/domain/AbstractDomainEvent.java
so can remove boilerplate casting in the app
=> ISIS-2753: changes AbstractDomainEvent#getSubject() to return <T> T

extensions/security/secman/applib/src/main/java/org/apache/isis/extensions/secman/applib/user/dom/ApplicationUser.java
Fix for ISIS-2967: Definition of maxlength in @Property and @Parameter for the @UserLocale in ApplicationUser
=> Fix for ISIS-2967: Definition of maxlength in @Property and @Parameter

.github/workflows/ci-build-artifacts-no-push-maven.yml, .github/workflows/ci-build-site-no-push.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions

antora/components/conguide/modules/ROOT/pages/contributing.adoc, starters/adoc/modules/starters/pages/simpleapp.adoc
This PR fixes some of the typos and formatting issues in these docs that I've come across.
=> ISIS-3243: fix typos and formatting in simpleapp and contribute docs

antora/components/conguide/modules/ROOT/pages/contributing.adoc
A proposal to extend the contributing doc to have a note for new contributors that they need to create an account and log in to Jira first before being able to create an issue for their contributions. 
This was from my personal experience when I first started contributing here, and as not all open-source projects have Jira set up as part of the contribution flow it might prove to be a potential source of confusion for others as well.
The text I've put in here for the PR is just a draft starting point - happy to amend it as required.
=> ISIS-3249: adds note on logging in to Jira for contribution

api/applib/src/main/java/module-info.java, api/applib/src/main/java/org/apache/causeway/applib/services/documentation/DocumentationService.java, api/applib/src/main/java/org/apache/causeway/applib/services/documentation/DocumentationServiceMenu.java, core/metamodel/src/main/java/module-info.java, core/runtimeservices/src/main/java/module-info.java, core/runtimeservices/src/main/java/org/apache/causeway/core/runtimeservices/documentation/DocumentationServiceDefault.java
We have created new documentation service which creates the HTML documentation based on the menu and the domain model. Very similar to the sitemap, but in HTML, so the end user can directly show it together with autogenerated description.
I've migrated it into the latest version, I've just hasn't been able to test it. At least it worked fine in ISIS M7.
=> ISIS-3328: HTML Documentation Service based on the domain model

api/applib/src/main/java/org/apache/causeway/applib/value/semantics/ValueDecomposition.java, extensions/vw/fullcalendar/applib/src/main/java/org/apache/causeway/extensions/fullcalendar/applib/value/CalendarEventSemantics.java, regressiontests/stable-rest/src/test/java/org/apache/causeway/testdomain/rest/RestServiceTest.java, regressiontests/stable/src/main/java/org/apache/causeway/testdomain/jdo/JdoInventoryResource.java, regressiontests/stable/src/main/java/org/apache/causeway/testdomain/util/rest/RestEndpointService.java, viewers/restfulobjects/applib/src/main/java/org/apache/causeway/viewer/restfulobjects/applib/dtos/ScalarValueDtoV2.java, viewers/restfulobjects/client/src/main/java/module-info.java, viewers/restfulobjects/client/src/main/java/org/apache/causeway/viewer/restfulobjects/client/ActionParameterListBuilder.java, viewers/restfulobjects/client/src/main/java/org/apache/causeway/viewer/restfulobjects/client/ResponseDigest.java, viewers/restfulobjects/client/src/main/java/org/apache/causeway/viewer/restfulobjects/client/ResponseDigester.java, viewers/restfulobjects/client/src/main/java/org/apache/causeway/viewer/restfulobjects/client/RestfulClient.java, viewers/restfulobjects/rendering/src/main/java/org/apache/causeway/viewer/restfulobjects/rendering/service/conneg/ContentNegotiationServiceOrgApacheCausewayV2.java, viewers/restfulobjects/rendering/src/main/java/org/apache/causeway/viewer/restfulobjects/rendering/service/valuerender/JsonValueEncoderServiceDefault.java, viewers/restfulobjects/viewer/src/main/java/org/apache/causeway/viewer/restfulobjects/viewer/resources/JsonParserHelper.java
Yet the REST transport is done using a base64 encoded string (in both directions).
For composites, can we ...
=> CAUSEWAY-3330: Composite value type support for RO

core/config/src/main/java/org/apache/causeway/core/config/CausewayConfiguration.java, core/metamodel/src/main/java/org/apache/causeway/core/metamodel/facets/object/domainobject/DomainObjectAnnotationFacetFactory.java, core/metamodel/src/test/java/org/apache/causeway/core/metamodel/facets/object/domainobject/DomainObjectAnnotationFacetFactoryTest.java
added support for allowing logical type names of an object also be defined as alias
=> CAUSEWAY-3598 logical type names of an object also be defined as alias

persistence/commons/src/main/java/org/apache/causeway/persistence/jpa/integration/changetracking/EntityChangeTrackerDefault.java, persistence/commons/src/main/java/org/apache/causeway/persistence/jpa/integration/changetracking/PreAndPostValueEvaluatorService.java, persistence/commons/src/main/java/org/apache/causeway/persistence/jpa/integration/changetracking/PreAndPostValueEvaluatorServiceDefault.java, persistence/jdo/datanucleus/src/main/java/org/apache/causeway/persistence/jdo/datanucleus/CausewayModulePersistenceJdoDatanucleus.java, persistence/jdo/datanucleus/src/main/java/org/apache/causeway/persistence/jdo/datanucleus/changetracking/PreAndPostValueEvaluatorServiceJdo.java
(ie EntityChangeTracker) to fine-tune whether an audit record needs to be published.  This works by overriding the default impl of PreAndPostValue, taking into account whether either the pre or the post is a Persistable, and if so whether it is also hollow for some reason
=> CAUSEWAY-3609: adds an SPI to allow JDO object store's impl of auditing

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/services/grid/bootstrap/GridSystemServiceBootstrap.java, regressiontests/stable-interact/src/test/java/org/apache/causeway/testdomain/interact/CollectionInteractionTest.java
in alphabetical order rather than according to their sequence.  Because the sequence (independent of its group) is hard to reason about
=> CAUSEWAY-3575: adds unbound/missing properties or collections

core/runtimeservices/src/main/java/org/apache/causeway/core/runtimeservices/message/MessageServiceDefault.java
to the session-scoped MessageBroker if there is no session.  As an approximation of this, we listen to whether the Metamodel is built yet.
=> CAUSEWAY-3579: adds a guard in MessageBroker to (try to) prevent calls

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/interactions/managed/ParameterNegotiationModel.java, core/metamodel/src/main/java/org/apache/causeway/core/metamodel/interactions/managed/PendingParamsSnapshot.java, core/metamodel/src/main/java/org/apache/causeway/core/metamodel/interactions/managed/PropertyNegotiationModel.java, core/metamodel/src/main/java/org/apache/causeway/core/metamodel/objectmanager/ObjectManager.java, viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/interaction/act/ActionInteractionWkt.java, viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/interaction/act/PendingParamsSnapshot.java
=> CAUSEWAY-3663: Snapshot Pending Param Values

api/applib/src/main/java/org/apache/causeway/applib/value/semantics/TemporalValueSemantics.java, core/metamodel/src/main/java/org/apache/causeway/core/metamodel/util/Facets.java, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarFragmentFactory.java, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarPanelFormFieldAbstract.html, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarPanelTextFieldAbstract.java, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarPanelTextFieldWithTemporalPicker.java, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/datepicker/TemporalDecomposition.java, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/datepicker/TextFieldWithDateTimePicker.java, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/pages/login/SignInPanelAbstract.java, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/util/Wkt.java, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/util/WktComponents.java, viewers/wicket/viewer/src/main/java/org/apache/causeway/viewer/wicket/viewer/registries/components/ComponentFactoryRegistrarDefault.java
=> CAUSEWAY-3489: Temporal Editing with Zone or Offset (Wicket Vwr)

api/applib/src/main/java/org/apache/causeway/applib/services/publishing/log/EntityPropertyChangeLogger.java, api/applib/src/main/java/org/apache/causeway/applib/services/publishing/spi/EntityPropertyChangeSubscriber.java, api/applib/src/main/java/org/apache/causeway/applib/services/repository/RepositoryService.java, core/config/src/main/java/org/apache/causeway/core/config/CausewayConfiguration.java, core/runtimeservices/src/main/java/org/apache/causeway/core/runtimeservices/publish/EntityPropertyChangePublisherDefault.java, extensions/security/audittrail/applib/src/main/java/org/apache/causeway/extensions/audittrail/applib/dom/AuditTrailEntryRepository.java, extensions/security/audittrail/applib/src/main/java/org/apache/causeway/extensions/audittrail/applib/dom/AuditTrailEntryRepositoryAbstract.java, extensions/security/audittrail/applib/src/main/java/org/apache/causeway/extensions/audittrail/applib/spiimpl/EntityPropertyChangeSubscriberForAuditTrail.java, persistence/commons/src/main/java/org/apache/causeway/persistence/commons/integration/repository/RepositoryServiceDefault.java, regressiontests/base/src/main/java/org/apache/causeway/testdomain/fixtures/EntityTestFixtures.java, regressiontests/base/src/main/java/org/apache/causeway/testdomain/jdo/JdoTestFixtures.java, regressiontests/base/src/main/java/org/apache/causeway/testdomain/jpa/JpaTestFixtures.java, regressiontests/persistence-jpa/src/test/java/org/apache/causeway/testdomain/persistence/jpa/JpaBootstrappingTest.java, regressiontests/publishing-jpa/src/test/java/org/apache/causeway/testdomain/publishing/jpa/JpaPropertyBulkPublishingTest.java, regressiontests/publishing-jpa/src/test/java/org/apache/causeway/testdomain/publishing/jpa/JpaPropertySinglePublishingTest.java
When handling large collections it may be beneficial to delay the commit for performance reasons.
This framework is a tread safe way to delay the committing. This only applies of the code is not used within transactional boundries already.
As an example of use the case of audit trail entry insertions in bulk is used.
=> Estup2-668 adding a bulk mode for the generic repository to enable delaying commits

viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarPanelFormFieldAbstract.html
As the combobox is to small in Safari this fix is needed to show the autocomplete combobox directly in the same with as the others fields in the dialog.
=> ESTUP2-674: Fix css for autocomplete

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/object/ManagedObjects.java, core/metamodel/src/main/java/org/apache/causeway/core/metamodel/object/MmSortUtils.java, core/metamodel/src/main/java/org/apache/causeway/core/metamodel/tabular/interactive/DataTableInteractive.java, core/metamodel/src/test/java/org/apache/causeway/core/metamodel/object/ManagedObjectTest.java, viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/interaction/coll/DataTableModelWkt.java, viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/collectioncontents/ajaxtable/CollectionContentsSortableDataProvider.java
=> CAUSEWAY-3772: Sorting on a collection of view models, hitting hollow exception

bom/pom.xml
Remove definition of `repository.apache.org` pointing to invalid URL.
1. Build [tries to download](https://github.com/apache/causeway/actions/runs/12346213801/job/34451461654#step:9:13083) non-Apache artifacts from Apache repo:
```
[INFO] Downloading from Apache Repository: https://repository.apache.org/org/assertj/assertj-bom/3.25.3/assertj-bom-3.25.3.pom
```
2. URL is wrong, [does not even work](https://github.com/apache/causeway/actions/runs/12346213801/job/34451461654#step:9:13051) for Apache artifacts:
```
[INFO] Downloading from Apache Repository: https://repository.apache.org/org/apache/activemq/activemq-bom/6.1.3/activemq-bom-6.1.3.pom
```
```
curl --head https://repository.apache.org/org/apache/activemq/activemq-bom/6.1.3/activemq-bom-6.1.3.pom
HTTP/1.1 404 Not Found
```
> …
=> CAUSEWAY-3840. Remove invalid repository.apache.org definition

CONTRIBUTING.adoc
Currently link on CONTRIBUTING.adoc routes to 404 due to milestone version in the path i.e. `2.0.0-M8`
This change fixes the path to use `latest` .
=> CAUSEWAY-3856: Fix link in CONTRIBUTING.adoc

valuetypes/markdown/adoc/modules/markdown/pages/about.adoc
This is the dependency name that works in 3.2.0
=> markdown persistence dependency for Wicket renamed

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/execution/ActionExecutor.java
I tested this with a one-off `causeway-app-simpleapp` `jpa` branch set to `3.0.0-SNAPHOT` and having the rename action be `SAFE_AND_REQUEST_CACHEABLE` with two parameters. The extra parameter might be incidental as I was focused on verifying the test failed.  It failed the integTest until I added this fix to the `main` branch.
=> Allows Action Semantics of SAFE_AND_REQUEST_CACHEABLE

valuetypes/markdown/adoc/modules/markdown/pages/about.adoc
In my testing, I found that the metamodel import is required and the persistence one has no effect.  My fork referenced in the ticket has the working SimpleApp V3-JPA with a Markdown property.
=> CAUSEWAY-3887 Metamodel and not Persistence import is required.

commons/src/test/java/org/apache/causeway/commons/collections/CanCompareTest.java, commons/src/test/java/org/apache/causeway/commons/collections/CanTest.java, commons/src/test/java/org/apache/causeway/commons/graph/GraphUtilsTest.java
Without this fix, using my non-US dafault locale I get:
```
/Users/john/Library/Java/JavaVirtualMachines/temurin-21.0.6/Contents/Home/bin/java -javaagent:/Users/john/Library/Caches/JetBrains/IntelliJIdea2025.1/captureAgent/debugger-agent.jar=file:///var/folders/57/2h75krjx6sx3h__x3l724l7m0000gp/T/capture16416934520741886359.props -ea -DisRunningWithSurefire=true -Xmx384m -XX:+EnableDynamicAgentLoading -Didea.test.cyclic.buffer.size=20478976 -javaagent:/Users/john/Applications/IntelliJ IDEA Ultimate.app/Contents/lib/idea_rt.jar=54880 -Dkotlinx.coroutines.debug.enable.creation.stack.trace=false -Ddebugger.agent.enable.coroutines=true -Dkotlinx.coroutines.debug.enable.flows.stack.trace=true -Dkotlinx.coroutines.debug.enable.mutable.state.flows.stack.trace=true --patch-module …
```
=> Fix String format locales to pass unit tests with non-US decimal format.
