apache/causeway

core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/EventBusServiceDefault.java

Exception message and class are not properly passed.

abortTransaction message on EXECUTED is incorrect

---

core/applib/src/main/java/org/apache/isis/applib/services/eventbus/EventBus.java
core/applib/src/main/java/org/apache/isis/applib/services/eventbus/EventBusService.java
core/runtime/pom.xml
core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/AxonEventListenerAdapter.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/AxonSimpleEventBusAdapter.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/AxonSimpleEventBusService.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/AxonSimpleEventBusServiceJdo.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/DefaultSubscriberExceptionHandler.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/EventBusAdapter.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/EventBusServiceDefault.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/GuavaEventBusAdapter.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/eventbus/RuntimeEventBusService.java
core/runtime/src/main/java/org/apache/isis/objectstore/jdo/datanucleus/service/eventbus/AxonSimpleEventBusServiceJdo.java

Initial implementation to be verified by Dan.
There are tests failing locally on "isis-core-runtime", but not sure they're related with this ...

ISIS-1028: Create Event Bus Service based on Axon

---

README.md

Apache Shiro URL was missing a dot

Apache Shiro URL was missing a dot

---

core/viewer-wicket/ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/reference/ReferencePanel.java

ISIS-1083 resetting dependent choice when selecting another referenced choice

ISIS-1083 resetting dependent choice when selecting another referenced choice

---

core/runtime/src/main/java/org/apache/isis/core/runtime/services/memento/Dom4jUtil.java
core/runtime/src/test/java/org/apache/isis/core/runtime/services/memento/MementoServiceDefaultTest.java

Added support for java.util.Date to MementoService

ISIS-1524: Dates not showing in view model

---

core/metamodel/src/main/java/org/apache/isis/core/metamodel/spec/feature/ObjectAction.java
core/runtime/src/main/java/org/apache/isis/core/runtime/system/persistence/PersistenceSession.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/actionmenu/serviceactions/CssMenuItem.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/actionmenu/serviceactions/ServiceActionUtil.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/widgets/linkandlabel/ActionLink.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/widgets/linkandlabel/ActionLinkFactoryAbstract.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/pages/bootstrap-overrides.css
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/panels/PanelUtil.java

+ ISIS-1619, blob/clob client side caching
+ ISIS-1625, tooltips for menu actions
+ ISIS-1626, confirmation dialog for no-parameter menu actions

Patchset to fix ISIS-1619, ISIS-1625, ISIS-1626

---

core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/entity/icontitle/EntityIconAndTitlePanel.java

Proposed fix for ISIS-1699
https://issues.apache.org/jira/browse/ISIS-1699

Fixes ISIS-1699 Titles of object references not shown in collections

---

core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/ScalarPanelAbstract2.java

It seems we need to be more specific about the current rendering context, when evaluating it against hiding advisors. In other words we need to distinguish between 3 different rendering contexts instead of just 2.
Proposed FIX for 
https://issues.apache.org/jira/browse/ISIS-1731

FIX ISIS-1731 @Property(hidden=Where.PARENTED_TABLES) does not render correctly

---

core/metamodel/src/main/java/org/apache/isis/core/metamodel/spec/feature/ObjectMember.java

Proposed fix for ISIS-1738
https://issues.apache.org/jira/browse/ISIS-1738
Inspired by Oscar's fix, this is a slightly refactored version of his.

FIX ISIS-1738

---

adocs/documentation/src/main/asciidoc/guides/ugfun/_ugfun_building-blocks_types-of-domain-objects_domain-entities.adoc

Trivial typo fix

---

core/metamodel/src/main/java/org/apache/isis/objectstore/jdo/metamodel/facets/prop/column/BigDecimalDerivedFromJdoColumnAnnotationFacetFactory.java
core/metamodel/src/main/java/org/apache/isis/objectstore/jdo/metamodel/facets/prop/column/MandatoryFromJdoColumnAnnotationFacetFactory.java
core/metamodel/src/main/java/org/apache/isis/objectstore/jdo/metamodel/facets/prop/column/MaxLengthDerivedFromJdoColumnAnnotationFacetFactory.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/changes/ChangedObjectsServiceInternal.java

Task-Url: https://issues.apache.org/jira/browse/ISIS-1985

ISIS-1985: fixes mm validation

---

core/log4j/src/main/java/org/apache/isis/core/runtime/logging/SnapshotServer.java
core/log4j/src/main/java/org/apache/isis/core/runtime/logging/SnapshotWriter.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/object/cssclassfa/annotation/CssClassFaFacetForDomainObjectLayoutFactory.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/object/cssclassfa/annotation/CssClassFaFacetForViewModelLayoutFactory.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/object/domainobjectlayout/CssClassFaFacetForDomainObjectLayoutAnnotation.java
core/runtime/src/main/java/org/apache/isis/objectstore/jdo/datanucleus/service/support/IsisJdoSupportImpl.java
core/viewer-wicket-impl/src/main/java/org/apache/isis/viewer/wicket/viewer/IsisWicketApplication.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/widgets/entitysimplelink/EntityLinkSimplePanel.java

Hope I didn't break anything. There seemed to be no tests covering the code I changed.

Isis 2056 fix sonar findings

---

core/applib/src/main/java/org/apache/isis/applib/annotation/Property.java
core/applib/src/main/java/org/apache/isis/applib/events/sse/EventStream.java
core/applib/src/main/java/org/apache/isis/applib/events/sse/EventStreamService.java
core/applib/src/main/java/org/apache/isis/applib/events/sse/EventStreamSource.java
core/applib/src/main/java/org/apache/isis/applib/util/JaxbAdapters.java
core/commons/pom.xml
core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/objectvalue/observe/ObserveFacet.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/objectvalue/observe/ObserveFacetAbstract.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/properties/property/PropertyAnnotationFacetFactory.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/properties/property/observe/ObserveFacetForPropertyAnnotation.java
core/pom.xml
core/runtime/src/main/java/org/apache/isis/core/runtime/services/background/BackgroundServiceDefault.java
core/runtime/src/main/java/org/apache/isis/core/runtime/services/sse/EventStreamServiceDefault.java
core/runtime/src/main/java/org/apache/isis/core/webapp/modules/WebModule.java
core/runtime/src/main/java/org/apache/isis/core/webapp/modules/WebModule_ServerSentEvents.java
core/runtime/src/main/java/org/apache/isis/core/webapp/modules/sse/ServerSentEventsServlet.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/actionmenu/serviceactions/ServiceActionsPanel.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/markup/MarkupComponent.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/markup/MarkupComponent_observing.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/markup/MarkupPanel.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/scalars/markup/ObservingComponent.js
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/errors/ExceptionStackTracePanel.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/util/SSESupport.java
core/viewer-wicket-ui/src/main/java/org/apache/isis/viewer/wicket/ui/util/SSESupport.js
migration-notes.adoc

Please consider the API extensions introduced with this SSE feature as not yet stable.

Introduces ServerSideEvents as an experimental feature.

---

.github/workflows/ci-workflow.yml
scripts/ci/core-gitlab-ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/isis/157)

ISIS-2167: initial CI workflow only printing mvn version

---

.m2/settings.xml
mixins/pom.xml
scripts/ci/build-mixins.sh

uses 'mvn versions:revert' to revert from 'mvn versions:set'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/isis/158)

ISIS-2167: github-ci: solving the mixin-build pom edit reversion

---

core/applib/src/test/java/org/apache/isis/applib/util/schema/Roundtrip.java
core/metamodel/src/test/java/org/apache/isis/metamodel/facets/propparam/specification/SpecificationAndTests.java
core/metamodel/src/test/java/org/apache/isis/metamodel/facets/propparam/specification/SpecificationNotTests.java
core/metamodel/src/test/java/org/apache/isis/metamodel/facets/propparam/specification/SpecificationOrTests.java
core/runtime-services/src/main/java/org/apache/isis/runtime/services/wrapper/AsyncWrapDefault.java
core/runtime/src/test/java/org/apache/isis/runtime/system/TypeExtractorMethodsParametersTest.java
core/viewers/restfulobjects/server/src/main/java/org/apache/isis/viewer/restfulobjects/server/util/UrlParserUtils.java
core/viewers/wicket/ui/src/test/java/org/apache/isis/viewer/wicket/ui/ComponentFactoryAbstractTest_init.java
extensions/lib/fakedata/impl/src/main/java/org/apache/isis/extensions/fakedata/dom/Addresses.java

remove empty lines

---

.asciidoctorconfig
.editorconfig
antora/components/security/modules/ROOT/pages/domain-services-api-for-applications.adoc
antora/components/toc/modules/ROOT/pages/downloads/how-to.adoc
antora/components/toc/modules/devguide/pages/asciidoc-syntax.adoc
antora/components/toc/modules/devguide/pages/contributing.adoc
antora/components/toc/modules/devguide/pages/ide/intellij.adoc
antora/components/userguide/modules/fun/.asciidoctorconfig
core/viewers/restfulobjects/src/main/doc/modules/ROOT/pages/about.adoc

I'm currently I've been trying out the AsciiDoc plugin for IntelliJ on this project. Each change is a single commit. Feel free to comment on each commit, and I will reword/remove/update them as needed and do a force-push afterwards.

ISIS-2258 asciidoc comments and suggestions

---

api/applib/src/main/java/org/apache/isis/applib/services/exceprecog/ExceptionRecognizerAbstract.java
api/applib/src/main/java/org/apache/isis/applib/services/exceprecog/ExceptionRecognizerForType.java
api/applib/src/test/java/org/apache/isis/applib/services/exceprecog/ExceptionRecognizerForTypeTest.java
api/applib/src/test/java/org/apache/isis/applib/services/exceprecog/ExceptionRecognizerGeneralTest.java
core/runtimeservices/src/main/java/org/apache/isis/core/runtimeservices/IsisModuleCoreRuntimeServices.java
core/runtimeservices/src/main/java/org/apache/isis/core/runtimeservices/recognizer/dae/ExceptionRecognizerForDataAccessException.java
core/runtimeservices/src/main/java/org/apache/isis/core/runtimeservices/recognizer/dae/impl/ExceptionRecognizerForOtherDataAccessProblem.java
viewers/wicket/ui/src/main/java/org/apache/isis/viewer/wicket/ui/panels/FormExecutorDefault.java

1. ExceptionRecognizerForDataAlreadyExists
2. ExceptionRecognizerForObjectNotFound
3. ExceptionRecognizerForRelatedDataExists
4. ExceptionRecognizerForUnableToSaveData
Also provide tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/isis/369)

ISIS-2502: wire up remaining specialized ExceptionRecognizers

---

viewers/wicket/viewer/src/main/java/org/apache/isis/viewer/wicket/viewer/integration/WebRequestCycleForIsis.java

Without this patch applied, when a user clicks a menu item in an expired
session, the session is simply refreshed and no action is taken. This is
a problem because from the user's point of view the click is ignored. This
patch fixes the problem by notifying user that the session was expired and
was refreshed from the click.

ISIS-1922: Notify user when expired session is refreshed

---

antora/components/conguide/modules/ROOT/pages/contributing.adoc
antora/components/conguide/modules/git/pages/about.adoc

chore: fix case of GitHub

---

viewers/wicket/ui/src/main/java/org/apache/isis/viewer/wicket/ui/panels/FormExecutorDefault.java

... to avoid resetting entity model if it won't be needed.  This also enables a workaround of annotating a delete action of a view model (wrapping an entity that is deleted during the action).

ISIS-2710: short-circuits check for redirectPolicy

---

examples/demo/web/src/main/java/demoapp/web/DemoAppManifestCommon.java
extensions/security/secman/adoc/modules/secman/pages/setting-up-with-shiro.adoc
extensions/security/secman/adoc/modules/secman/pages/setting-up.adoc
extensions/security/secman/adoc/modules/secman/partials/module-nav.adoc
extensions/security/secman/applib/src/main/java/org/apache/isis/extensions/secman/applib/IsisModuleExtSecmanApplib.java
extensions/security/secman/applib/src/main/java/org/apache/isis/extensions/secman/applib/SecmanAutoConfiguration.java
extensions/security/secman/integration/src/main/java/org/apache/isis/extensions/secman/integration/authenticator/AuthenticatorSecman.java
extensions/security/secman/integration/src/main/java/org/apache/isis/extensions/secman/integration/authenticator/AuthenticatorSecmanAutoConfiguration.java
extensions/security/secman/integration/src/main/java/org/apache/isis/extensions/secman/integration/authorizor/AuthorizorSecman.java
extensions/security/secman/integration/src/main/resources/META-INF/spring.factories
extensions/security/secman/shiro-realm/src/main/java/org/apache/isis/extensions/secman/shiro/IsisModuleExtSecmanRealmShiro.java
mavendeps/adoc/modules/mavendeps/pages/about.adoc
mavendeps/webapp/pom.xml

ISIS-2557: decouples secman from shiro

---

antora/components/userguide/modules/fun/pages/drop-downs-and-defaults.adoc
antora/components/userguide/modules/fun/pages/object-members/actions.adoc
api/applib/src/main/java/org/apache/isis/applib/annotation/DomainObject.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/facets/object/domainobject/DomainObjectAnnotationFacetFactory.java
core/metamodel/src/test/java/org/apache/isis/core/metamodel/facets/object/domainobject/DomainObjectAnnotationFacetFactoryTest.java
extensions/security/secman/persistence-jdo/src/main/java/org/apache/isis/extensions/secman/jdo/role/dom/ApplicationRole.java
extensions/security/secman/persistence-jdo/src/main/java/org/apache/isis/extensions/secman/jdo/tenancy/dom/ApplicationTenancy.java
extensions/security/secman/persistence-jdo/src/main/java/org/apache/isis/extensions/secman/jdo/user/dom/ApplicationUser.java
extensions/security/secman/persistence-jpa/src/main/java/org/apache/isis/extensions/secman/jpa/role/dom/ApplicationRole.java
extensions/security/secman/persistence-jpa/src/main/java/org/apache/isis/extensions/secman/jpa/tenancy/dom/ApplicationTenancy.java
extensions/security/secman/persistence-jpa/src/main/java/org/apache/isis/extensions/secman/jpa/user/dom/ApplicationUser.java

ISIS-2659: renames 'autoCompleteAction' 

---

api/applib/src/main/java/org/apache/isis/applib/mixins/metamodel/Object_downloadMetamodelXml.java
api/applib/src/main/java/org/apache/isis/applib/services/metamodel/Config.java
api/applib/src/main/java/org/apache/isis/applib/services/metamodel/DomainMember.java
api/applib/src/main/java/org/apache/isis/applib/services/metamodel/MetaModelService.java
api/applib/src/main/java/org/apache/isis/applib/services/metamodel/MetaModelServiceMenu.java
api/applib/src/test/java/org/apache/isis/applib/services/metamodel/MetaModelService_Config_Test.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/inspect/Object_inspectMetamodel.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/services/metamodel/DomainMemberDefault.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/services/metamodel/MetaModelExporter.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/services/metamodel/MetaModelServiceDefault.java
regressiontests/stable-domainmodel/src/test/java/org/apache/isis/testdomain/domainmodel/AnnotationSyntesizerTest.java
regressiontests/stable-domainmodel/src/test/java/org/apache/isis/testdomain/domainmodel/DomainModelTest_usingGoodDomain.java

Isis 2712 : adds ability to download metamodel XML based on namespace prefix

---

commons/src/main/java/org/apache/isis/commons/internal/ioc/_IocContainer.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/context/MetaModelContext.java

... returns the first by priority.
In addition:
- deletes #getSingleton, was unused
- adds javadoc

ISIS-2762: makes getSingletonElseFail less strict

---

api/applib/src/main/java/org/apache/isis/applib/services/repository/RepositoryService.java
extensions/security/secman/applib/src/main/java/org/apache/isis/extensions/secman/applib/role/dom/ApplicationRoleRepositoryAbstract.java
extensions/security/secman/persistence-jpa/src/main/java/org/apache/isis/extensions/secman/jpa/user/dom/ApplicationUser.java

Also programmatically persists changes to both ApplicationUser and ApplicationRole afterwards

ISIS-2763: changes user/role mapping to CascadeType of MERGE, PERSIST

---

core/metamodel/src/main/java/org/apache/isis/core/metamodel/objectmanager/identify/ObjectBookmarker.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/objectmanager/identify/ObjectBookmarker_builtinHandlers.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/objectmanager/load/ObjectLoader.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/objectmanager/load/ObjectLoader_builtinHandlers.java

(cherry picked from commit 4235fcf6dcb1f2a5edc1ff46d57176b41afd8cd2)
(cherry picked from commit 6a39aae328fbcb34b1b64d773bf1d9ae6ef84c61)

ISIS-2779: adds bookmarkers and loaders for serializable view models.

---

antora/playbooks/site-testing.yml
antora/playbooks/site.yml
core/pom.xml
mavendeps/archtests/pom.xml
mavendeps/pom.xml
testing/adoc/modules/ROOT/partials/component-nav.adoc
testing/archtestsupport/adoc/antora.yml
testing/archtestsupport/adoc/modules/archtestsupport/nav.adoc
testing/archtestsupport/adoc/modules/archtestsupport/pages/about.adoc
testing/archtestsupport/adoc/modules/archtestsupport/partials/module-nav.adoc
testing/archtestsupport/applib/pom.xml
testing/archtestsupport/applib/src/main/java/org/apache/isis/testing/archtestsupport/applib/IsisModuleTestingArchTestSupportApplib.java
testing/archtestsupport/applib/src/main/java/org/apache/isis/testing/archtestsupport/applib/classrules/ArchitectureClassRules.java
testing/archtestsupport/applib/src/main/java/org/apache/isis/testing/archtestsupport/applib/modulerules/ArchitectureModuleRules.java
testing/archtestsupport/applib/src/main/java/org/apache/isis/testing/archtestsupport/applib/packagerules/ArchitecturePackageRules.java
testing/archtestsupport/applib/src/main/java/org/apache/isis/testing/archtestsupport/applib/packagerules/Subpackage.java
testing/archtestsupport/applib/src/main/java/org/apache/isis/testing/archtestsupport/applib/packagerules/SubpackageEnum.java
testing/archtestsupport/applib/src/main/java/org/apache/isis/testing/archtestsupport/applib/packagerules/SubpackageType.java
testing/archtestsupport/pom.xml
testing/pom.xml

Isis 2781 : initial take-on of archtest rules

---

antora/components/refguide/modules/applib-classes/pages/layout.adoc
antora/components/refguide/modules/applib-classes/pages/layout/column-order.adoc
api/applib/src/main/java/org/apache/isis/applib/annotation/Where.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/IsisModuleCoreMetamodel.java
core/metamodel/src/main/java/org/apache/isis/core/metamodel/services/tablecol/TableColumnOrderServiceUsingTxtFile.java
core/metamodel/src/test/java/org/apache/isis/core/metamodel/services/tablecol/Customer#orders.columnOrder.txt
core/metamodel/src/test/java/org/apache/isis/core/metamodel/services/tablecol/Order.columnOrder.txt
core/metamodel/src/test/java/org/apache/isis/core/metamodel/services/tablecol/TableColumnOrderServiceUsingTxtFile_Test.java
extensions/security/spring-oauth2/src/main/java/org/apache/isis/extensions/spring/security/oauth2/authconverters/AuthenticationConverterOfOAuth2UserPrincipal.java
viewers/wicket/ui/src/main/java/org/apache/isis/viewer/wicket/ui/components/entity/icontitle/EntityIconAndTitlePanel.java

ISIS-2813: adds TableColumnOrderServiceUsingTxtFile

---

api/applib/src/main/java/org/apache/isis/applib/annotation/DomainObject.java
api/applib/src/main/java/org/apache/isis/applib/annotation/DomainService.java

for @Named and logicalTypeName; also objectType

ISIS-2754: adds AliasFor to DomainService and DomainObject

---

viewers/wicket/ui/src/main/java/org/apache/isis/viewer/wicket/ui/pages/home/HomePage.java

(cherry picked from commit 16eb40a5caa4405c2199468162a8ae4e450a805f)

ISIS-2730: catches exception and falls back to welcome page

---

core/pom.xml

https://issues.apache.org/jira/browse/ISIS-2977

ISIS-2977: Use secure version of jdom

---

api/applib/src/main/java/org/apache/causeway/applib/services/command/Command.java
extensions/adoc/modules/ROOT/partials/module-nav.adoc
extensions/core/commandlog/adoc/modules/commandlog/pages/about.adoc
extensions/core/commandlog/applib/pom.xml
extensions/core/commandlog/applib/src/main/java/org/apache/causeway/extensions/commandlog/applib/CausewayModuleExtCommandLogApplib.java
extensions/core/commandlog/applib/src/main/java/org/apache/causeway/extensions/commandlog/applib/dom/BackgroundService.java
extensions/core/commandlog/applib/src/main/java/org/apache/causeway/extensions/commandlog/applib/dom/CommandLogEntry.java
extensions/core/commandlog/applib/src/main/java/org/apache/causeway/extensions/commandlog/applib/dom/CommandLogEntryRepository.java
extensions/core/commandlog/applib/src/main/java/org/apache/causeway/extensions/commandlog/applib/dom/ExecuteIn.java
extensions/core/commandlog/applib/src/main/java/org/apache/causeway/extensions/commandlog/applib/job/RunBackgroundCommandsJob.java
extensions/core/commandlog/applib/src/main/java/org/apache/causeway/extensions/commandlog/applib/subscriber/CommandSubscriberForCommandLog.java
extensions/core/commandlog/applib/src/test/java/org/apache/causeway/extensions/commandlog/applib/integtest/BackgroundService_IntegTestAbstract.java
extensions/core/commandlog/persistence-jdo/src/main/java/org/apache/causeway/extensions/commandlog/jdo/dom/CommandLogEntry.java
extensions/core/commandlog/persistence-jdo/src/test/java/org/apache/causeway/extensions/commandlog/jdo/integtests/AppManifest.java
extensions/core/commandlog/persistence-jdo/src/test/java/org/apache/causeway/extensions/commandlog/jdo/integtests/BackgroundService_IntegTest.java
extensions/core/commandlog/persistence-jpa/src/main/java/org/apache/causeway/extensions/commandlog/jpa/dom/CommandLogEntry.java
extensions/core/commandlog/persistence-jpa/src/test/java/org/apache/causeway/extensions/commandlog/jpa/integtests/AppManifest.java
extensions/core/commandlog/persistence-jpa/src/test/java/org/apache/causeway/extensions/commandlog/jpa/integtests/BackgroundService_IntegTest.java
extensions/core/commandlog/persistence-jpa/src/test/java/org/apache/causeway/extensions/commandlog/jpa/integtests/CommandLog_IntegTest.java
extensions/core/commandlog/pom.xml
testing/integtestsupport/applib/src/main/java/org/apache/causeway/testing/integtestsupport/applib/CausewayInteractionHandler.java

also changes design of CommandLogEntry, persist parentInteractionId rather than parent reference, and reinstate executeIn enum attribute

ISIS-3267 : adds BackgroundService

---

core/config/src/main/java/org/apache/causeway/core/config/CausewayConfiguration.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/specloader/SpecificationLoaderDefault.java
core/security/src/main/java/module-info.java
core/security/src/main/java/org/apache/causeway/core/security/authorization/manager/ActionSemanticsResolver.java
core/security/src/main/java/org/apache/causeway/core/security/authorization/manager/AuthorizationManager.java
regressiontests/stable-interact/src/test/java/org/apache/causeway/testdomain/interact/ActionInteractionTest_notUsingAllowSafeSemantics.java
regressiontests/stable-interact/src/test/java/org/apache/causeway/testdomain/interact/ActionInteractionTest_usingAllowSafeSemantics.java
regressiontests/stable/src/main/java/org/apache/causeway/testdomain/model/interaction/InteractionDemo.java

CAUSEWAY-3358: Allow SAFE semantics actions to be invoked with only VIEWING permission

---

commons/src/main/java/org/apache/causeway/commons/internal/base/_Refs.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/interactions/managed/ParameterNegotiationModel.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/interactions/managed/PropertyNegotiationModel.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/spec/feature/ObjectActionParameter.java
viewers/commons/model/src/main/java/org/apache/causeway/viewer/commons/model/scalar/UiParameter.java
viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/ChainingObjectModel.java
viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/ScalarModel.java
viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/_Xray.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/actions/ActionParametersForm.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/property/PropertyEditForm.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarPanelAbstract.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarPanelAbstract2.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarPanelFormFieldAbstract.html
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarPanelFormFieldAbstract.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/ScalarPanelSelectAbstract.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/_Util.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/bool/BooleanPanel.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/choices/ObjectChoicesSelect2Panel.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/choices/ValueChoicesSelect2Panel.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/scalars/image/JavaAwtImagePanel.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/widgets/select2/Select2.java

CAUSEWAY-3425: broken repaint decision logic

---

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/object/MmEntityUtils.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/services/objectlifecycle/ObjectLifecyclePublisher.java
core/runtimeservices/src/main/java/org/apache/causeway/core/runtimeservices/publish/ObjectLifecyclePublisherDefault.java
core/transaction/src/main/java/org/apache/causeway/core/transaction/changetracking/EntityChangeTracker.java
persistence/commons/src/main/java/org/apache/causeway/persistence/jpa/integration/changetracking/EntityChangeTrackerDefault.java
persistence/jdo/datanucleus/src/main/java/org/apache/causeway/persistence/jdo/datanucleus/changetracking/JdoLifecycleListener.java
persistence/jpa/applib/src/main/java/org/apache/causeway/persistence/jpa/applib/integration/CausewayEntityListener.java

Make that _Property Change Publishing_ code a bit more readable.

CAUSEWAY-3324: Property Change Publishing Refactoring

---

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/object/ManagedObject.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/objectmanager/ObjectManager.java
core/runtimeservices/src/main/java/org/apache/causeway/core/runtimeservices/command/SchemaValueMarshallerDefault.java
core/runtimeservices/src/main/java/org/apache/causeway/core/runtimeservices/wrapper/WrapperFactoryDefault.java

from plain pojos - leverage metamodel.
Also, setNull for ParamDto if the ManagedObject is empty

CAUSEWAY-3555: improves WrapperFactory's creation of ManagedObject

---

core/config/src/main/java/org/apache/causeway/core/config/CausewayConfiguration.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/facets/objectvalue/digits/MinFractionalDigitsFacetAbstract.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/facets/value/semantics/MaxFractionalDigitsFacetFromJavaxValidationDigitsAnnotation.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/facets/value/semantics/MinFractionalDigitsFacetFromJavaxValidationDigitsAnnotation.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/facets/value/semantics/ValueSemanticsAnnotationFacetFactory.java
persistence/jdo/metamodel/src/main/java/org/apache/causeway/persistence/jdo/metamodel/facets/prop/column/BigDecimalFromJdoColumnAnnotationFacetFactory.java
persistence/jdo/metamodel/src/main/java/org/apache/causeway/persistence/jdo/metamodel/facets/prop/column/MinFractionalDigitsFacetFromJdoColumnAnnotation.java
persistence/jpa/metamodel/src/main/java/org/apache/causeway/persistence/jpa/metamodel/facets/prop/column/BigDecimalFromJpaColumnAnnotationFacetFactory.java
persistence/jpa/metamodel/src/main/java/org/apache/causeway/persistence/jpa/metamodel/facets/prop/column/MinFractionalDigitsFacetFromJpaColumnAnnotation.java
viewers/wicket/ui-test/src/test/java/org/apache/causeway/viewer/wicket/ui/test/components/scalars/jdkmath/BigDecimalConverterTest.java

... from @Digits#fraction, or JDO/JPA @Column#scale, if configured

CAUSEWAY-3592: adds support to derive MinFractionalDigitsFacet

---

api/applib/src/main/java/org/apache/causeway/applib/services/tablecol/TableColumnOrderForCollectionTypeAbstract.java
api/applib/src/main/java/org/apache/causeway/applib/services/tablecol/TableColumnOrderService.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/services/tablecol/TableColumnOrderServiceDefault.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/services/tablecol/TableColumnOrderServiceUsingTxtFile.java
core/metamodel/src/test/java/org/apache/causeway/core/metamodel/services/tablecol/Customer#_.Order4.columnOrder.txt
core/metamodel/src/test/java/org/apache/causeway/core/metamodel/services/tablecol/Customer#_.Order5.columnOrder.fallback.txt
core/metamodel/src/test/java/org/apache/causeway/core/metamodel/services/tablecol/Customer#moreOrders.columnOrder.fallback.txt
core/metamodel/src/test/java/org/apache/causeway/core/metamodel/services/tablecol/Order.columnOrder.txt
core/metamodel/src/test/java/org/apache/causeway/core/metamodel/services/tablecol/Order3.columnOrder.fallback.txt
core/metamodel/src/test/java/org/apache/causeway/core/metamodel/services/tablecol/TableColumnOrderServiceUsingTxtFile_Test.java

and cleans up existing impl a little, updates out-of-date javadoc

CAUSEWAY-3599: implements new logic

---

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/spec/feature/ObjectAssociation.java

assignable in either directoin

CAUSEWAY-3583: generalized the check

---

viewers/restfulobjects/rendering/src/main/java/org/apache/causeway/viewer/restfulobjects/rendering/service/swagger/internal/_OpenApiModelFactory.java

as per https://swagger.io/docs/specification/2-0/authentication/basic-authentication/

CAUSEWAY-3615: adds 'security' item to openapi

---

extensions/vw/exceldownload/wicket-ui/src/main/java/org/apache/causeway/extensions/exceldownload/wkt/ui/CausewayModuleExtExcelDownloadWicketUi.java
extensions/vw/exceldownload/wicket-ui/src/main/java/org/apache/causeway/extensions/exceldownload/wkt/ui/viewer/CellStyleProvider.java
extensions/vw/exceldownload/wicket-ui/src/main/java/org/apache/causeway/extensions/exceldownload/wkt/ui/viewer/CollectionContentsAsExcelFactory.java
extensions/vw/exceldownload/wicket-ui/src/main/java/org/apache/causeway/extensions/exceldownload/wkt/ui/viewer/ExcelFileDownloadLink.java
extensions/vw/exceldownload/wicket-ui/src/main/java/org/apache/causeway/extensions/exceldownload/wkt/ui/viewer/ExcelFileModel.java
extensions/vw/exceldownload/wicket-ui/src/main/java/org/apache/causeway/extensions/exceldownload/wkt/ui/viewer/_TimeConversion.java

CAUSEWAY-3613: moves excel download classes into correct package

---

extensions/security/secman/integration/src/main/java/org/apache/causeway/extensions/secman/integration/usermementorefiner/UserMementoRefinerFromApplicationUser.java

Couldn't find a way to add a unit test.

CAUSEWAY-3618 add roles to user memento during the refining stage

---

antora/components/refguide-index/modules/applib/pages/index/services/grid/GridSystemService.adoc
antora/components/refguide/modules/applib-classes/partials/layout/menubars.adoc
antora/components/refguide/modules/applib-classes/partials/layout/object-layout.adoc
antora/components/refguide/modules/applib-svc/partials/_metadata-spi.adoc
antora/components/userguide/modules/ROOT/partials/ui-layout-and-hints/object-layout.adoc
api/applib/src/main/java/org/apache/causeway/applib/annotation/CollectionLayout.java
api/applib/src/main/java/org/apache/causeway/applib/annotation/PropertyLayout.java
api/applib/src/main/java/org/apache/causeway/applib/services/grid/GridSystemService.java
core/config/src/main/java/org/apache/causeway/core/config/CausewayConfiguration.java
core/config/src/main/java/org/apache/causeway/core/config/metamodel/facets/AssociationLayoutConfigOptions.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/_testing/MetaModelContext_forTesting.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/services/grid/bootstrap/GridSystemServiceBootstrap.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/services/grid/bootstrap/_UnreferencedSequenceUtil.java
core/metamodel/src/test/java/org/apache/causeway/core/metamodel/facets/actions/action/ActionAnnotationFacetFactoryTest_executionPublishing.java
regressiontests/stable-interact/src/test/java/org/apache/causeway/testdomain/interact/CollectionInteractionTest.java
regressiontests/stable/src/main/java/org/apache/causeway/testdomain/util/interaction/DomainObjectTesterFactory.java

CAUSEWAY-3575: [Layout] Allow for slot-in order of unreferenced associations to be configured either sequence-based or alphabetica

---

extensions/security/secman/integration/src/main/java/org/apache/causeway/extensions/secman/integration/authorizor/AuthorizorSecman.java

CAUSEWAY-3517: adds special case logic to always allow logout

---

api/applib/src/main/java/module-info.java
api/applib/src/main/java/org/apache/causeway/applib/CausewayModuleApplib.java
api/applib/src/main/java/org/apache/causeway/applib/services/columnorder/ColumnOrderTxtFileService.java
api/applib/src/main/java/org/apache/causeway/applib/services/columnorder/Object_downloadColumnOrderTxtFilesAsZip.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/CausewayModuleCoreMetamodel.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/inspect/CausewayModuleCoreMetamodelMixins.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/inspect/Object_inspectMetamodel.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/services/columnorder/ColumnOrderTxtFileServiceDefault.java
extensions/vw/pdfjs/metamodel/src/test/java/org/apache/causeway/extensions/pdfjs/metamodel/PdfjsViewer_MixinDomainWithPdfJsViewer_IntegTest.dump_facets.approved.xml
extensions/vw/pdfjs/metamodel/src/test/java/org/apache/causeway/extensions/pdfjs/metamodel/PdfjsViewer_MixinDomain_IntegTest.dump_facets.approved.xml
extensions/vw/pdfjs/metamodel/src/test/java/org/apache/causeway/extensions/pdfjs/metamodel/PdfjsViewer_PropDomainWithPdfjsViewer_IntegTest.dump_facets.approved.xml
extensions/vw/pdfjs/metamodel/src/test/java/org/apache/causeway/extensions/pdfjs/metamodel/PdfjsViewer_PropDomain_IntegTest.dump_facets.approved.xml
regressiontests/stable-domainmodel/src/test/java/org/apache/causeway/testdomain/domainmodel/MetaModelRegressionTest.verify.approved.xml

to applib, introducing new domain service to enable this

CAUSEWAY-3597: moves downloadColumnOrderTxtFileAsZip mixin

---

bom/pom.xml
core/config/src/main/java/org/apache/causeway/core/config/CausewayModuleCoreConfig.java
core/internaltestsupport/pom.xml
core/metamodel/pom.xml
core/pom.xml
persistence/jpa/eclipselink/pom.xml
starters/pom.xml
testing/integtestsupport/applib/pom.xml
testing/pom.xml
tooling/cli/pom.xml
tooling/pom.xml

Spring Boot 3.2 (Java 21 baseline)

---

regressiontests/stable-layouts/src/test/java/org/apache/causeway/regressiontests/layouts/integtest/Layout_Counter_IntegTest.java
regressiontests/stable-layouts/src/test/java/org/apache/causeway/regressiontests/layouts/integtest/Layout_SimpleObject_IntegTest.java

temporarily comments out failing tests - they will be reinstated in 3655.

Causeway 3579

---

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/interactions/managed/PendingParamsSnapshot.java
viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/interaction/act/ActionInteractionWkt.java

CAUSEWAY-3674: Potential NPE in PendingParamsSnapshot

---

core/pom.xml
security/simple/pom.xml
security/simple/src/main/adoc/antora.yml
security/simple/src/main/adoc/modules/simple/nav.adoc
security/simple/src/main/adoc/modules/simple/pages/about.adoc
security/simple/src/main/adoc/modules/simple/partials/module-nav.adoc
security/simple/src/main/java/module-info.java
security/simple/src/main/java/org/apache/causeway/security/simple/CausewayModuleSecuritySimple.java
security/simple/src/main/java/org/apache/causeway/security/simple/authentication/SimpleAuthenticator.java
security/simple/src/main/java/org/apache/causeway/security/simple/authorization/SimpleAuthorizor.java
security/simple/src/main/java/org/apache/causeway/security/simple/realm/SimpleRealm.java
security/simple/src/test/java/org/apache/causeway/security/simple/SecuritySimpleAuthTest.java

CAUSEWAY-3698: Security Integration Replacement for Shiro INI based Realm

---

persistence/jpa/adoc/modules/ROOT/pages/setup-and-configuration.adoc

add MODE=LEGACY for H2 and EclipseLink

Updates setup-and-configuration.adoc

---

viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/ScalarParameterModel.java

.. by extending Wicket's ScalarParameterModel

CAUSEWAY-3753: adds additional validation of per params

---

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/interactions/managed/ParameterNegotiationModel.java
viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/ScalarModel.java
viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/models/ScalarParameterModel.java

Refactors new logic into underlying `Param Negotiation Model`.

CAUSEWAY-3753: refactors new logic into underlying Param Negotiation

---

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/util/snapshot/XmlSnapshot.java
viewers/restfulobjects/viewer/src/main/java/org/apache/causeway/viewer/restfulobjects/viewer/webmodule/CausewayRestfulObjectsInteractionFilter.java

CAUSEWAY-3789 output array's values instead of memory address

CAUSEWAY-3789 output array's values instead of memory address

---

core/metamodel/src/main/java/org/apache/causeway/core/metamodel/context/MetaModelContext.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/tabular/DataTableInteractive.java
core/metamodel/src/main/java/org/apache/causeway/core/metamodel/tabular/internal/DataTableInternal.java
viewers/wicket/model/src/main/java/module-info.java
viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/tableoption/PageActionChoice.java
viewers/wicket/model/src/main/java/org/apache/causeway/viewer/wicket/model/tableoption/PagesizeChoice.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/collectioncontents/ajaxtable/CollectionContentsAsAjaxTablePanel.css
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/collectioncontents/ajaxtable/CollectionContentsAsAjaxTablePanel.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/collectioncontents/ajaxtable/CollectionContentsSortableDataProvider.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/table/CausewayAjaxDataTable.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/table/DataTableWithPagesAndFilter.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/table/head/HeadersToolbarAbstract.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/table/nav/NavigationToolbar.html
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/table/nav/NavigationToolbar.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/table/nav/pageact/PageActionChooser.html
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/table/nav/pageact/PageActionChooser.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/table/nav/pagesize/PagesizeChooser.html
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/table/nav/pagesize/PagesizeChooser.java

CAUSEWAY-3808: Support for table page specific actions

---

commons/src/main/java/org/apache/causeway/commons/graph/GraphUtils.java
commons/src/test/java/org/apache/causeway/commons/graph/GraphUtilsTest.java

CAUSEWAY-3812: [Commons] GraphUtils adds sorting and advanced edge

---

extensions/vw/tabular/excel/src/main/java/org/apache/causeway/extensions/tabular/excel/exporter/ExcelCellWriter.java
extensions/vw/tabular/excel/src/main/java/org/apache/causeway/extensions/tabular/excel/exporter/ExcelFileWriter.java
extensions/vw/tabular/pdf/src/main/java/org/apache/causeway/extensions/tabular/pdf/CausewayModuleExtTabularPdf.java
extensions/vw/tabular/pdf/src/main/java/org/apache/causeway/extensions/tabular/pdf/exporter/PdfFileWriter.java
extensions/vw/tabular/pdf/src/main/java/org/apache/causeway/extensions/tabular/pdf/exporter/TabularPdfExporter.java
extensions/vw/tabular/pdf/src/main/java/org/apache/causeway/extensions/tabular/pdf/factory/CellFactory.java
extensions/vw/tabular/pdf/src/main/java/org/apache/causeway/extensions/tabular/pdf/factory/PdfFactory.java
extensions/vw/tabular/pdf/src/main/java/org/apache/causeway/extensions/tabular/pdf/factory/PdfTable.java

CAUSEWAY-3854: PDF Tabular Export

---

bom/pom.xml
viewers/commons/prism/pom.xml
viewers/commons/prism/src/main/java/module-info.java
viewers/commons/prism/src/main/java/org/apache/causeway/viewer/commons/prism/PrismHighlighter.java
viewers/commons/prism/src/main/java/org/apache/causeway/viewer/commons/prism/PrismLanguage.java
viewers/commons/prism/src/main/java/org/apache/causeway/viewer/commons/prism/PrismNodeHighlighter.java
viewers/commons/prism/src/main/java/org/apache/causeway/viewer/commons/prism/PrismTheme.java
viewers/commons/prism/src/main/java/org/apache/causeway/viewer/commons/prism/PrismUtils.java
viewers/wicket/ui/src/main/java/module-info.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/attributes/markup/HighlightBehavior.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/components/attributes/markup/MarkupComponent_reloadJs.java
viewers/wicket/ui/src/main/java/org/apache/causeway/viewer/wicket/ui/util/PrismResourcesWkt.java

CAUSEWAY-3857: do prism syntax highlighting server side
